sudo: required
os: osx
language: node_js
node_js: '8'
     
include:
  - osx_image: xcode9.2
    env: PLATFORM_VERSION=10.12

before_script:
  - "Xvfb :99 -ac -screen 0 1024x768x8 &"
  - sleep 3
  
script:
  - npm install
  - ./node_modules/.bin/appium-doctor --ios
  - ./node_modules/.bin/appium &
  - sleep 30
  - npm run nightwatch-cucumber-travis-ios -- --tag iostest
