sudo: required
os: osx
language: node_js
node_js: '7'
     
include:
    - osx_image: xcode9.3
      env: DEVICE=11.3

before_script:
  - "sudo Xvfb :99 -ac -screen 0 1024x768x8 &"
#   - "export DISPLAY=:99.0"
#   - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  
script:
#   - brew install libimobiledevice --HEAD 
#   - npm install -g ios-deploy
  - npm install -g appium
  - npm install
  - ./node_modules/.bin/appium-doctor --ios
  - appium &
  - sleep 20
  - npm run nightwatch-cucumber-travis-ios -- --tag iostest --verbose
