sudo: required
os: osx
language: node_js
node_js: '7'
     
include:
  - osx_image: xcode9.3beta
  - env: DEVICE=11.3
before_script:
  - "sudo Xvfb :99 -ac -screen 0 1024x768x8 &"
#   - "export DISPLAY=:99.0"
#   - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  
script:
#   - brew install libimobiledevice --HEAD 
#   - npm install -g ios-deploy
#   - "sh -c lsof -P | grep ':4723' | awk '{print $2}' | xargs kill -9"
  - npm install -g appium
  - npm install
  - ./node_modules/.bin/appium-doctor --ios
  - ./node_modules/.bin/appium &
  - sleep 30
  - npm run nightwatch-cucumber-travis-ios -- --tag iostest
