sudo: required
os: osx
language: node_js
node_js: '8'
osx_image: xcode9.3

before_script:
  - "ps -axco command | sort | uniq"
  - sleep 5
#   - "Xvfb :99 -ac -screen 0 1024x768x8 &"
# #   - sleep 3
  
# script:
#   - npm install
#   - ./node_modules/.bin/appium-doctor --ios
#   - appium &
#   - sleep 10
#   - npm run nightwatch-cucumber-travis-ios -- --tag iostest
