sudo: required
os: osx
language: node_js
node_js: '8'
osx_image: xcode9.3

before_script:
  - brew cask install xquartz
  - "Xvfb :99 -ac -screen 9 1024x768x8"
  - sleep 3
  
script:
  - npm install
  - ./node_modules/.bin/appium-doctor --ios
  - ./node_modules/.bin/appium &
  - sleep 10
  - npm run nightwatch-cucumber-travis-ios -- --tag iostest
