language: node_js

node_js:
  - '7'
  
addons:
  firefox: latest
  apt:
    sources:
     - google-chrome
    packages:
     - google-chrome-stable

before_script:
  - "Xvfb :99 & export DISPLAY=:99"
  - sleep 3
  
install:
  - npm install
  - npm run selenium-install
  - sleep 10
  
script:
  - npm run nightwatch-cucumber-travis
