sudo: required
os: osx
language: node_js
node_js: '8'
osx_image: xcode9.3

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
#   - brew cask install xquartz
#   - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then ( sudo Xvfb :99 -ac -screen 9 1024x768x8; echo ok )& fi
#   - sleep 3
  
script:
  - npm install
  - ./node_modules/.bin/appium-doctor --ios
  - ./node_modules/.bin/appium &
  - sleep 10
  - npm run nightwatch-cucumber-travis-ios -- --tag iostest
