sudo: required
os: osx
language: node_js
node_js: '7'
     
addons:
  apt:
    packages:
     - xvfb
 include:
    - osx_image: xcode9.2
      env: DEVICE=10.3
 before_script:
     - "sudo Xvfb :99 -ac -screen 0 1024x768x8 &"
  
script:
  - npm install -g iproxy
  - npm install -g appium
  - appium &
  - sleep 10
  - npm run nightwatch-cucumber-travis-ios -- --tag iostest
 
