sudo: required
os: osx
language: node_js
node_js: '8'
osx_image: xcode9.3

before_script:
  - "ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null 2> /dev/null ; brew install caskroom/cask/brew-cask 2> /dev/null"
  - brew cask install xquartz
  - "Xvfb :99 -ac -screen 4 1024x768x8 &"
  - sleep 3
  
# script:
#   - npm install
#   - ./node_modules/.bin/appium-doctor --ios
#   - appium &
#   - sleep 10
#   - npm run nightwatch-cucumber-travis-ios -- --tag iostest
