sudo: required
os: osx
language: node_js
node_js: '7'
     
include:
    - osx_image: xcode9.2
      env: DEVICE=11.2

script:
  - npm install -g appium
  - appium &
  - npm install
  - npm run selenium-install
  - npm run nightwatch-cucumber-travis-ios
 
