sudo: required
os: osx
language: node_js
node_js: '8'
osx_image: xcode9.3

before_script:
  - git clone https://github.com/XQuartz/quartz-wm.git
  - cd quartz-wm
  - "ACLOCAL="aclocal -I /opt/X11/share/aclocal" autoreconf -fvi"
  - "PKG_CONFIG_PATH=/opt/X11/share/pkgconfig:/opt/X11/lib/pkgconfig ./configure --prefix=/opt/X11"
  - make
  - "Xvfb :99 -ac -screen 4 1024x768x8 &"
  - sleep 3
  
# script:
  - npm install
  - ./node_modules/.bin/appium-doctor --ios
  - appium &
  - sleep 10
  - npm run nightwatch-cucumber-travis-ios -- --tag iostest
