sudo: required
os: osx
language: node_js
node_js: '7'
     
include:
  - osx_image: xcode9.3beta
  - env: DEVICE=11.3
before_script:
  - "Xvfb :99 -ac -screen 0 1024x768x8 &"
  - sleep 3
  
script:
  - npm install
  - ./node_modules/.bin/appium-doctor --ios
  - ./node_modules/.bin/appium &
  - sleep 30
  - npm run nightwatch-cucumber-travis-ios -- --tag iostest
