language: node_js
node_js:
  - '7'
addons:
  apt:
    packages:
      - xvfb
before_script:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm run selenium-install
  - npm run selenium &
  
script:
  - npm run nightwatch-cucumber-chrome
