sudo: required
os: osx
language: node_js
node_js: '7'
     
addons:
  apt:
    packages:
     - xvfb
     
include:
    - osx_image: xcode9.2
      env: DEVICE=11.2

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  
script:
  - npm install -g appium
  - appium &
  - npm install
  - npm run selenium-install
  - npm run nightwatch-cucumber-travis-ios
 
