sudo: required
os: osx
language: node_js
node_js: '7'
     
addons:
  apt:
    packages:
     - xvfb
     
include:
    - osx_image: xcode9.2
      env: DEVICE=10.3
  
script:
  - npm install -g appium
  - appium &
  - npm install
  - npm run selenium-install
  - npm run nightwatch-cucumber-travis-ios
 
