sudo: required
os: osx
language: node_js
node_js: '8'
osx_image: xcode9.3

before_script:
#   - brew cask install xquartz
  - "Xvfb :1234 & export DISPLAY=:1234"
  - sleep 3
  
script:
  - npm install
  - ./node_modules/.bin/appium-doctor --ios
  - ./node_modules/.bin/appium &
  - sleep 10
  - npm run nightwatch-cucumber-travis-ios -- --tag iostest
