sudo: required
os: osx
language: node_js
node_js: '7'
     
include:
    - osx_image: xcode9.2
      env: DEVICE=11.2

before_script:
  - sudo Xvfb :99 -ac -screen 0 1024x768x8; echo ok )& ; fi
#   - "export DISPLAY=:99.0"
#   - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  
script:
  - npm install -g appium
  - appium &
  - sleep 10
  - npm install
  - npm run nightwatch-cucumber-travis-ios -- --tag iostest
